export enum StyleCode {
  ResetAll = "0",
  Bold = "1",
  ResetBold = "22",
  Dim = "2",
  ResetDim = "22",
  Italic = "3",
  ResetItalic = "23",
  Underline = "4",
  ResetUnderline = "24",
  Blinking = "5",
  ResetBlinking = "25",
  Inverse = "7",
  ResetInverse = "27",
  Hidden = "8",
  ResetHidden = "28",
  Strikethrough = "9",
  ResetStrikethrough = "29",
}
